### ISSUE TITLE
相談：見直しチェック(お気に入り登録機能)について

### ISSUE THREAD

**Issue by kumasuke6** [kumasuke6/kokushi-app#13]
## 前提
[非同期通信(js)](https://github.com/kumasuke6/kokushi-app/blob/master/src/resources/views/exam.blade.php#L164-L187)
[Controller](https://github.com/kumasuke6/kokushi-app/blob/master/src/app/Http/Controllers/ExamController.php#L63-L70)

見直しチェック(お気に入り登録機能)は上記箇所でjsの非同期通信にて行うようにしています。
jsの非同期通信を採用したのは以下のような理由です。

1. PHPでの更新よりも非同期通信で即時反映された方がユーザーの意図通りに動くと感じたため。
2. 問題終了後の遷移先が複数あるため、PHPで処理を書こうとすると複数個所に記載することになるため。

## 相談内容
気になっている点は見直しチェックボタンが連打された場合にリクエストが増えてしまうため、サーバー負荷は少しかかるなと感じています。

## 補足
- フロントの実装は普段しないのでより良い実装方法やご意見などがあれば教えていただきたいです。気にしすぎな感じもしているので問題なければそれでも大丈夫です！
- 総当たり攻撃的にやられたらどうしようもないので、ユーザーが増えてる状態でかつ悪意なく何度か押してしまった場合を想定しています。

**Comment by Sado4** [comment]
チェックボタンを押したタイミングで保存処理などを行う方法は、仰るとおりあまり望ましくないかもしれません。
下記のどちらかに変更するのが望ましいかと思います！

- debouncing処理を追加する
JavaScriptのlodashなどのライブラリを使ってdebouncing処理をすることで、一定時間内に連続して複数のリクエストが発生した場合には、最後のリクエストのみを送信し、それ以外はキャンセルすることができる。

- Formのsubmitイベントを待つ
HTML上に<form>要素を追加し、その中にチェックボックスを配置し、submitイベントを発生させるようにする。
それにより、一度にまとめてデータを送信することで、サーバーに対して負荷をかけなくなる。

**Comment by kumasuke6** [comment]
@Sado4 
コメントありがとうございます！

> debouncing処理を追加する
JavaScriptのlodashなどのライブラリを使ってdebouncing処理をすることで、一定時間内に連続して複数のリクエストが発生した場合には、最後のリクエストのみを送信し、それ以外はキャンセルすることができる。

こちらの方法で進めていこうと思います！

**Comment by kumasuke6** [comment]
対応済み
